name: build
on:
  push:
    branches:
      - "main"
jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "16.14"
      - uses: actions/setup-go@v3
        with:
          go-version: "1.18.2"
      - name: Setup
        run: | 
          npm install -g pnpm
          go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - name: Frontend env
        run: |
          touch ./frontend/.env
          echo VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }} >> ./frontend/.env
          echo VITE_OAUTH_URL=${{ secrets.VITE_OAUTH_URL }} >> ./frontend/.env
          cat ./frontend/.env
          mkdir ./frontend/dist
          touch ./frontend/dist/index.html
      - name: Build
        run: |
          wails generate module
          wails build -ldflags "-X main.clientId=${{ secrets.CLIENT_ID }}"
      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::UserBuild_$(date +"%Y.%m.%d_%H-%M")"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: build/degabut.app
